version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080" # Serves both API and frontend
    environment:
      - GO_ENV=development
    depends_on:
      - db
    volumes:
      - upload_data:/app/uploads
      - ./backend:/app/backend
      - ./frontend:/app/frontend

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  upload_data:
