FROM golang:1.22-alpine

WORKDIR /app

# Copy only necessary files first
COPY backend/go.mod .
RUN go mod download

# Copy the rest of the application
COPY backend/ .

# Build the application
RUN go build -o main cmd/server/main.go

EXPOSE 8080

CMD ["./main"] 